dll_path = r"k:\temp\dll\mupen64plus.dll"
input_plugin_path = r"k:\temp\dll\mupen64plus-input-sdl.dll"
video_plugin_path = r"k:\temp\dll\mupen64plus-video-rice.dll"
#video_plugin_path = r"k:\temp\dll\mupen64plus-video-glide64mk2.dll"
rsp_plugin_path = r"k:\temp\dll\mupen64plus-rsp-hle.dll"